apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-flask-deployment
  namespace: meme
spec:
  replicas: 4  # Number of desired replicas (adjust as needed)
  selector:
    matchLabels:
      app: meme-flask
  template:
    metadata:
      labels:
        app: meme-flask
    spec:
      containers:
      - name: meme-flask
        image: sshuen30/flask-app:latest  # Replace with your Docker image name and tag
        ports:
        - containerPort: 5001
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 30
